### ISSUE TITLE
Vision Processing

### ISSUE THREAD

**Issue by IrishConman** [FRCTeam3206/2023-Winter-Season#4]
Implement vision processing so we can use the April Tags in both auton and teleop. Drive code not necessary, but preferred 

### Due Date: Start ASAP, Provide weekly progress reports

**Comment by GrandMoff100** [comment]
@IrishConman Do you also want game piece recognition? Or is that out of scope right now?

**Comment by GrandMoff100** [comment]
April tags are a go!
