### ISSUE TITLE
Autonomous

### ISSUE THREAD

**Issue by IrishConman** [FRCTeam3206/2023-Winter-Season#5]
Create 4 stages of autonomous modes to compensate for potential breakdowns and difficulties on comp day

The 4 stages must include:
1.  Very Basic
2. Basic
3. Moderate
4. Ambitious

**Very Basic -** Simple movement. Leave the starting position and drive out of the community
**Basic -** Very Basic + deposit held game piece before driving out of the community
**Moderate -** The preferred auton mode; Basic + picking up another piece and maneuvering to a good spot for teleop
**Ambitious -** The best case scenario; Moderate + depositing as many pieces as possible and optionally moving to a good spot

Please consult Carter or me for more information on each specific stage, if necessary

### Due Date: Variable
    > Very Basic - Feb 8
    > Basic - Feb 11
    > Moderate - Feb 18
    > Ambitious - Get it done when you can

**Comment by GrandMoff100** [comment]
**TODO:** Split up into smaller issues.

**Comment by IrishConman** [comment]
This issue has been split into smaller issues, and is no longer necessary
